"""External data sources for the dashboard.

Coin prices are fetched live from CoinGecko when possible, with a PostgreSQL
cache and a static fallback so the dashboard never fails just because the
external API is slow or unavailable. Market news is fetched live from
CryptoPanic when an API key is configured, with static fallback news
otherwise. The AI Insight of the Day is generated by OpenRouter when a key
and model are configured, with a deterministic fallback insight otherwise or
if the AI response fails a basic safety check. The meme is selected from a
small static catalog, deterministically per user per day.
"""

import hashlib
from datetime import datetime, timezone

import httpx
from sqlalchemy.orm import Session

from app.config import settings
from app.models import CachedCoinPrice, UserPreferences

COINGECKO_URL = "https://api.coingecko.com/api/v3/simple/price"
COINGECKO_TIMEOUT_SECONDS = 5.0

COINGECKO_IDS: dict[str, str] = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "SOL": "solana",
    "ADA": "cardano",
    "XRP": "ripple",
    "DOGE": "dogecoin",
    "AVAX": "avalanche-2",
    "LINK": "chainlink",
    "MATIC": "matic-network",
    "DOT": "polkadot",
}

# Final backup if both CoinGecko and the PostgreSQL cache are unavailable for an asset.
STATIC_COIN_PRICES: dict[str, dict[str, object]] = {
    "BTC": {"name": "Bitcoin", "priceUsd": 65000.0, "change24h": 2.4},
    "ETH": {"name": "Ethereum", "priceUsd": 3400.0, "change24h": 1.1},
    "SOL": {"name": "Solana", "priceUsd": 145.0, "change24h": 5.6},
    "ADA": {"name": "Cardano", "priceUsd": 0.45, "change24h": -1.2},
    "XRP": {"name": "XRP", "priceUsd": 0.62, "change24h": 0.8},
    "DOGE": {"name": "Dogecoin", "priceUsd": 0.15, "change24h": 3.9},
    "AVAX": {"name": "Avalanche", "priceUsd": 28.0, "change24h": -0.5},
    "LINK": {"name": "Chainlink", "priceUsd": 14.5, "change24h": 2.1},
    "MATIC": {"name": "Polygon", "priceUsd": 0.78, "change24h": -2.3},
    "DOT": {"name": "Polkadot", "priceUsd": 6.9, "change24h": 1.7},
}

CRYPTOPANIC_URL = "https://cryptopanic.com/api/v1/posts/"
CRYPTOPANIC_TIMEOUT_SECONDS = 5.0
MIN_USEFUL_NEWS_ITEMS = 2
MAX_NEWS_ITEMS = 4

# Final backup if CRYPTOPANIC_API_KEY is missing, the request fails, or it
# doesn't return enough useful results.
# Long-form demo copy: fake, clearly-labeled ("Static Fallback") articles used
# only when CryptoPanic isn't configured. Written at real-article length so the
# "Read full article" modal has something substantial to show, not a one-liner.
STATIC_NEWS: list[dict[str, object]] = [
    {
        "id": "fallback-news-btc-1",
        "title": "Bitcoin remains central to market attention",
        "summary": (
            "Bitcoin continues to be one of the most closely watched assets in the crypto market, "
            "with its price action often setting the tone for the broader sector. Analysts across "
            "the space point to a mix of macroeconomic conditions, institutional flows, and on-chain "
            "activity as the main threads shaping sentiment this week.\n\n"
            "Trading volume has remained elevated across major exchanges, and long-term holders "
            "continue to make up a significant share of circulating supply — a pattern many market "
            "watchers view as a sign of conviction rather than short-term speculation. Discussion "
            "around Bitcoin's role as a macro hedge also continues to resurface whenever traditional "
            "markets show volatility.\n\n"
            "This is general market context, not a trading recommendation. Conditions can shift "
            "quickly, and past patterns are not a guarantee of future behavior."
        ),
        "source": "Static Fallback",
        "relatedAssets": ["BTC"],
        "url": None,
        "isFallback": True,
    },
    {
        "id": "fallback-news-eth-1",
        "title": "Ethereum network activity stays in focus",
        "summary": (
            "Ethereum's network usage and developer activity remain a common reference point for "
            "investors watching the broader ecosystem, with the chain continuing to host the largest "
            "share of decentralized applications, stablecoin activity, and on-chain value of any "
            "smart contract platform.\n\n"
            "Layer-2 scaling networks built on top of Ethereum have kept gas fees on the base layer "
            "relatively predictable, while developer tooling and documentation continue to mature. "
            "Several ecosystem projects have highlighted incremental protocol improvements aimed at "
            "efficiency and scalability rather than any single dramatic overhaul.\n\n"
            "None of this should be read as a signal to buy or sell — it's simply a snapshot of "
            "where attention in the ecosystem is currently concentrated."
        ),
        "source": "Static Fallback",
        "relatedAssets": ["ETH"],
        "url": None,
        "isFallback": True,
    },
    {
        "id": "fallback-news-sol-1",
        "title": "Solana ecosystem continues to draw developer interest",
        "summary": (
            "Solana's ecosystem has seen continued project activity, a trend investors are watching "
            "as part of broader market context. The network's throughput and low transaction costs "
            "continue to attract builders experimenting with consumer-facing applications, gaming, "
            "and payments use cases.\n\n"
            "Community discussion has also centered on network stability improvements following past "
            "periods of congestion, with several infrastructure upgrades proposed or already rolled "
            "out by core contributors. Total value locked across Solana-based protocols has "
            "fluctuated alongside the broader market rather than moving independently.\n\n"
            "As with any ecosystem still iterating quickly, activity levels can change from week to "
            "week, and this summary reflects general context rather than a recommendation."
        ),
        "source": "Static Fallback",
        "relatedAssets": ["SOL"],
        "url": None,
        "isFallback": True,
    },
    {
        "id": "fallback-news-general-1",
        "title": "Crypto markets show mixed movement today",
        "summary": (
            "Major assets moved in different directions today, reflecting a lack of a single "
            "dominant market theme. Rather than a broad risk-on or risk-off move, trading desks have "
            "described the session as \"rotational,\" with capital shifting between sectors of the "
            "market rather than flowing uniformly in or out.\n\n"
            "Some analysts point to thinner-than-usual trading volume as a contributing factor, which "
            "can amplify price swings on both sides without necessarily reflecting a change in "
            "longer-term positioning. Others note that mixed macro signals — from interest rate "
            "expectations to broader risk appetite — have left traders without a clear consensus to "
            "trade around.\n\n"
            "This may be relevant context for your briefing, but it isn't a signal to act on any "
            "particular asset."
        ),
        "source": "Static Fallback",
        "relatedAssets": [],
        "url": None,
        "isFallback": True,
    },
    {
        "id": "fallback-news-regulation-1",
        "title": "Regulatory developments remain a key risk factor",
        "summary": (
            "Regulatory news continues to be one of the most closely watched risk factors for crypto "
            "investors, underscoring the value of staying risk-aware. Jurisdictions around the world "
            "continue to take different approaches to digital asset oversight, from clearer licensing "
            "frameworks in some regions to more cautious, enforcement-driven postures in others.\n\n"
            "Market participants have generally welcomed greater regulatory clarity where it has "
            "emerged, viewing it as a precondition for more institutional participation over time — "
            "even when the specific rules themselves add near-term compliance overhead. Ongoing "
            "discussions about stablecoin oversight and exchange licensing remain some of the most "
            "closely tracked threads in this space.\n\n"
            "Regulatory developments can shift quickly and vary significantly by region, so this is "
            "offered as general awareness rather than guidance specific to any jurisdiction."
        ),
        "source": "Static Fallback",
        "relatedAssets": [],
        "url": None,
        "isFallback": True,
    },
    {
        "id": "fallback-news-sentiment-1",
        "title": "Market sentiment stays mixed among investors",
        "summary": (
            "Investor sentiment surveys show a mixed outlook this week, with no strong consensus "
            "emerging in either direction. Retail-focused sentiment indices and derivatives "
            "positioning data both point to a market that is neither broadly euphoric nor broadly "
            "fearful — a contrast to the sharper swings seen during past cycles.\n\n"
            "Some commentators read this kind of equilibrium as a sign of a maturing market with a "
            "broader base of participants and more diverse time horizons. Others caution that "
            "sentiment can turn quickly once a clear catalyst emerges, whether from macro data, a "
            "major protocol event, or a shift in regulatory posture.\n\n"
            "However you read it, sentiment data is just one input among many, and shouldn't be "
            "treated as a standalone signal."
        ),
        "source": "Static Fallback",
        "relatedAssets": [],
        "url": None,
        "isFallback": True,
    },
]

# Served straight from the frontend's static /memes/ folder (frontend/public/memes/),
# the same way favicon.svg is served -- no external image host, no API.
MEME_CATALOG: list[dict[str, object]] = [
    {
        "id": "meme-1",
        "title": "Taking profits (or not)",
        "caption": "Me: taking profits. Also me: but it could 10x.",
        "imageUrl": "/memes/taking-profits.png",
        "source": "static",
    },
    {
        "id": "meme-2",
        "title": "Checking the portfolio",
        "caption": "Ok, check the price... 911, I'm dying.",
        "imageUrl": "/memes/checking-the-price.png",
        "source": "static",
    },
    {
        "id": "meme-3",
        "title": "Crypto then vs. now",
        "caption": "We solved the Byzantine Generals' Problem. Now: \"coin has dog?\"",
        "imageUrl": "/memes/crypto-then-vs-now.png",
        "source": "static",
    },
    {
        "id": "meme-4",
        "title": "Should I sell my Bitcoin?",
        "caption": "The chart says it all: no, and no — but in red.",
        "imageUrl": "/memes/should-i-sell-bitcoin.png",
        "source": "static",
    },
    {
        "id": "meme-5",
        "title": "This is fine",
        "caption": "Portfolio down across the board? This is fine.",
        "imageUrl": "/memes/this-is-fine.png",
        "source": "static",
    },
    {
        "id": "meme-6",
        "title": "How crypto works",
        "caption": "It's ok, I'll just HODL and buy more. Two months later...",
        "imageUrl": "/memes/how-crypto-works.png",
        "source": "static",
    },
    {
        "id": "meme-7",
        "title": "Diamond hands, exhausted",
        "caption": "When you invest everything in crypto and just... lie there.",
        "imageUrl": "/memes/diamond-hands-exhausted.png",
        "source": "static",
    },
]

_INVESTOR_PHRASES = {
    "HODLer": "long-term holders",
    "Day Trader": "day traders watching short-term moves",
    "NFT Collector": "collectors keeping half an eye on the broader market",
    "Beginner": "newer investors still getting a feel for the market",
    "Researcher": "anyone digging into the underlying patterns",
}

_RISK_PHRASES = {
    "Low": "steadier, lower-volatility context",
    "Medium": "a mix of steady context and notable swings",
    "High": "the kind of volatility that comes with a higher risk tolerance",
}

# Alternate phrasings the deterministic insight rotates through when asked to
# avoid repeating a previously-rejected insight (see `_deterministic_insight`'s
# `variant` param). Same underlying data, different wording/framing.
_INSIGHT_OPENERS = [
    "{lead}",
    "Here's today's read: {lead}",
    "Quick market pulse: {lead}",
]

_INSIGHT_CLOSERS = [
    "For {investor_phrase}, this is the kind of move worth keeping on the radar alongside {risk_phrase}.",
    "That's a detail {investor_phrase} may want to keep in view, especially with {risk_phrase} in mind.",
    "Something for {investor_phrase} to note, given {risk_phrase}.",
]


def _fetch_live_prices(symbols: list[str]) -> dict[str, dict[str, object]] | None:
    """Try to fetch live prices from CoinGecko. Returns None on any failure."""
    ids = [COINGECKO_IDS[symbol] for symbol in symbols if symbol in COINGECKO_IDS]
    if not ids:
        return None

    params = {"ids": ",".join(ids), "vs_currencies": "usd", "include_24hr_change": "true"}
    headers = {"x-cg-demo-api-key": settings.coingecko_api_key} if settings.coingecko_api_key else {}

    try:
        response = httpx.get(COINGECKO_URL, params=params, headers=headers, timeout=COINGECKO_TIMEOUT_SECONDS)
        response.raise_for_status()
        data = response.json()
    except Exception as exc:  # network errors, timeouts, bad JSON, non-2xx status, etc.
        print(f"[integrations] CoinGecko request failed, falling back: {exc}")
        return None

    id_to_symbol = {coingecko_id: symbol for symbol, coingecko_id in COINGECKO_IDS.items()}
    results: dict[str, dict[str, object]] = {}
    for coingecko_id, values in data.items():
        symbol = id_to_symbol.get(coingecko_id)
        if symbol is None or "usd" not in values:
            continue
        results[symbol] = {
            "name": STATIC_COIN_PRICES.get(symbol, {}).get("name", symbol),
            "priceUsd": float(values["usd"]),
            "change24h": float(values.get("usd_24h_change") or 0.0),
        }

    return results or None


def _save_cached_prices(db: Session, live_prices: dict[str, dict[str, object]]) -> None:
    fetched_at = datetime.now(timezone.utc)
    for symbol, values in live_prices.items():
        cached = db.query(CachedCoinPrice).filter(CachedCoinPrice.symbol == symbol).first()
        if cached is None:
            cached = CachedCoinPrice(symbol=symbol)
            db.add(cached)
        cached.name = values["name"]
        cached.price_usd = values["priceUsd"]
        cached.change_24h = values["change24h"]
        cached.fetched_at = fetched_at
    db.commit()


def _get_cached_prices(db: Session, symbols: list[str]) -> dict[str, CachedCoinPrice]:
    rows = db.query(CachedCoinPrice).filter(CachedCoinPrice.symbol.in_(symbols)).all()
    return {row.symbol: row for row in rows}


def _coin_price_item(symbol: str, name: str, price_usd: float, change_24h: float, is_fallback: bool, source: str) -> dict[str, object]:
    return {
        "id": f"price-{symbol}",
        "symbol": symbol,
        "name": name,
        "priceUsd": price_usd,
        "change24h": change_24h,
        "isFallback": is_fallback,
        "source": source,
    }


def get_coin_prices(assets: list[str], db: Session) -> list[dict[str, object]]:
    """Return prices for the given assets: live from CoinGecko where possible,
    otherwise the last cached price from PostgreSQL, otherwise static fallback
    data. Only returns items for assets we actually support."""
    symbols = [symbol.upper() for symbol in assets if symbol.upper() in COINGECKO_IDS]
    if not symbols:
        return []

    live_prices = _fetch_live_prices(symbols) or {}
    if live_prices:
        _save_cached_prices(db, live_prices)

    cached_prices = _get_cached_prices(db, symbols)

    results: list[dict[str, object]] = []
    for symbol in symbols:
        if symbol in live_prices:
            live = live_prices[symbol]
            results.append(_coin_price_item(symbol, live["name"], live["priceUsd"], live["change24h"], False, "live"))
        elif symbol in cached_prices:
            cached = cached_prices[symbol]
            results.append(
                _coin_price_item(symbol, cached.name, cached.price_usd, cached.change_24h or 0.0, True, "cache")
            )
        elif symbol in STATIC_COIN_PRICES:
            static = STATIC_COIN_PRICES[symbol]
            results.append(
                _coin_price_item(symbol, static["name"], static["priceUsd"], static["change24h"], True, "static")
            )

    return results


def _rank_news(matched: list[dict[str, object]], rest: list[dict[str, object]], exclude_ids: set[str]) -> list[dict[str, object]]:
    """Build a news list from matched items first, then the rest, skipping any
    item whose id is in exclude_ids (previously downvoted by the user)."""
    news: list[dict[str, object]] = []
    for item in matched + rest:
        if item["id"] in exclude_ids or item in news:
            continue
        news.append(item)
        if len(news) >= MAX_NEWS_ITEMS:
            break
    return news


def _top_up(news: list[dict[str, object]], pool: list[dict[str, object]], minimum: int) -> list[dict[str, object]]:
    """If news has fewer than the minimum useful items, add items back from
    the full pool (in order, including ones already excluded) only until the
    minimum is met — never resetting to the whole pool at once, so as few
    previously-downvoted items resurface as possible."""
    if len(news) >= minimum:
        return news
    topped_up = list(news)
    for item in pool:
        if len(topped_up) >= minimum:
            break
        if item not in topped_up:
            topped_up.append(item)
    return topped_up


def _static_news(assets: list[str], downvoted_ids: set[str] | None = None) -> list[dict[str, object]]:
    downvoted_ids = downvoted_ids or set()
    selected = set(assets)
    matched = [item for item in STATIC_NEWS if set(item["relatedAssets"]) & selected]
    general = [item for item in STATIC_NEWS if not item["relatedAssets"]]

    news = _rank_news(matched, general, downvoted_ids)
    news = _top_up(news, matched + general, MIN_USEFUL_NEWS_ITEMS)

    return news[:MAX_NEWS_ITEMS]


def _fetch_live_news(symbols: list[str]) -> list[dict[str, object]] | None:
    """Try to fetch live crypto news from CryptoPanic. Returns None if no API
    key is configured, the request fails, or there are no usable results."""
    if not settings.cryptopanic_api_key:
        return None

    params = {"auth_token": settings.cryptopanic_api_key, "public": "true", "kind": "news"}
    if symbols:
        params["currencies"] = ",".join(symbols)

    try:
        response = httpx.get(CRYPTOPANIC_URL, params=params, timeout=CRYPTOPANIC_TIMEOUT_SECONDS)
        response.raise_for_status()
        data = response.json()
    except Exception as exc:  # network errors, timeouts, bad JSON, non-2xx status, etc.
        print(f"[integrations] CryptoPanic request failed, falling back: {exc}")
        return None

    news_items: list[dict[str, object]] = []
    for index, item in enumerate(data.get("results") or []):
        title = item.get("title")
        if not title:
            continue
        related = [c["code"].upper() for c in item.get("currencies") or [] if c.get("code")]
        source_title = (item.get("source") or {}).get("title") or "a news source"
        news_items.append(
            {
                "id": f"cryptopanic-{item.get('id', index)}",
                "title": title,
                "summary": f"Coverage from {source_title}, shared as market context. Not a trading recommendation.",
                "source": "Crypto News",
                "relatedAssets": related,
                "url": item.get("url"),
                "isFallback": False,
            }
        )

    return news_items or None


def get_market_news(assets: list[str], downvoted_ids: set[str] | None = None) -> list[dict[str, object]]:
    """Return 2-4 market news items: live from CryptoPanic when an API key is
    configured and the request returns enough useful results, otherwise
    static fallback news. Fallback news prefers items related to the given
    assets, padded out with general market news. Items the user has
    previously downvoted are skipped where possible (never at the cost of
    returning fewer than the minimum useful items)."""
    symbols = [symbol.upper() for symbol in assets]
    downvoted_ids = downvoted_ids or set()

    live_news = _fetch_live_news(symbols)
    if live_news and len(live_news) >= MIN_USEFUL_NEWS_ITEMS:
        selected = set(symbols)
        matched = [item for item in live_news if set(item["relatedAssets"]) & selected]
        rest = [item for item in live_news if item not in matched]
        news = _rank_news(matched, rest, downvoted_ids)
        news = _top_up(news, matched + rest, MIN_USEFUL_NEWS_ITEMS)
        return news[:MAX_NEWS_ITEMS]

    return _static_news(symbols, downvoted_ids)


def pick_meme(user_id: int, downvoted_ids: set[str] | None = None) -> dict[str, object]:
    """Pick one meme from the static catalog, stable for a given user for the
    whole day so a dashboard refresh doesn't change it, but different across
    users and days. Uses a stable hash (not Python's randomized built-in
    hash()) so the choice survives backend restarts. Memes the user has
    previously downvoted are excluded from the pool, unless that would leave
    no memes to choose from."""
    downvoted_ids = downvoted_ids or set()
    pool = [meme for meme in MEME_CATALOG if meme["id"] not in downvoted_ids] or MEME_CATALOG

    today = datetime.now(timezone.utc).date().isoformat()
    digest = hashlib.sha256(f"{user_id}-{today}".encode()).hexdigest()
    index = int(digest, 16) % len(pool)
    return {**pool[index], "isFallback": True}


OPENROUTER_TIMEOUT_SECONDS = 10.0

_AI_SYSTEM_PROMPT = (
    "You are writing a short, engaging 'AI Insight of the Day' for a crypto dashboard. Write like "
    "an interesting daily briefing, not a form letter: never explain why you're telling the user "
    "this (do not say things like 'because you selected' or 'you described yourself as'), and do "
    "not add a financial-advice disclaimer sentence — the app already shows one separately, so "
    "repeating it would be redundant. "
    "You must not provide financial advice, investment instructions, trading signals, or price "
    "predictions. Do not tell the user to buy, sell, hold, trade, enter, exit, or invest. Keep it "
    "to 1-2 short, natural-sounding paragraphs."
)

# Post-generation safety net for the live path. Deliberately checks for "is financial advice"
# rather than the bare phrase, so that if the model still mentions financial advice at all, only
# an affirmative claim ("this is financial advice") is flagged, not a safe negated one.
_UNSAFE_PHRASES = [
    "buy now",
    "you should buy",
    "sell now",
    "you should sell",
    "you should invest",
    "guaranteed profit",
    "will pump",
    "will definitely rise",
    "will definitely go up",
    "invest now",
    "trade now",
    "enter a position",
    "exit a position",
    "is financial advice",
]


def _contains_unsafe_wording(text: str) -> bool:
    lowered = text.lower()
    return any(phrase in lowered for phrase in _UNSAFE_PHRASES)


def _summarize_feedback(feedback_items: list[dict[str, object]] | None) -> str:
    if not feedback_items:
        return "No feedback history yet."

    upvoted = {item["sectionType"] for item in feedback_items if item.get("vote") == "UP"}
    downvoted = {item["sectionType"] for item in feedback_items if item.get("vote") == "DOWN"}

    parts = []
    if upvoted:
        parts.append(f"previously upvoted: {', '.join(sorted(upvoted))}")
    if downvoted:
        parts.append(f"previously downvoted: {', '.join(sorted(downvoted))}")

    return f"User has {'; '.join(parts)}." if parts else "No strong feedback pattern yet."


def _build_ai_context(
    preferences: UserPreferences,
    coin_prices: list[dict[str, object]],
    market_news: list[dict[str, object]],
    feedback_items: list[dict[str, object]] | None,
) -> str:
    lines = [
        "User profile:",
        f"- Investor type: {preferences.investor_type}",
        f"- Selected assets: {', '.join(preferences.assets)}",
        f"- Preferred content types: {', '.join(preferences.content_types)}",
        f"- Risk level: {preferences.risk_level}",
        "",
        "Coin price data:",
    ]
    for price in coin_prices:
        lines.append(
            f"- {price['symbol']}: ${price['priceUsd']:.2f}, 24h change {price['change24h']:.1f}%, "
            f"source: {price['source']}"
        )

    lines.append("")
    lines.append("Market news:")
    for item in market_news[:MAX_NEWS_ITEMS]:
        related = ", ".join(item["relatedAssets"]) or "general"
        lines.append(f"- {item['title']} ({related}): {item['summary']}")

    lines.append("")
    lines.append(f"User feedback history: {_summarize_feedback(feedback_items)}")

    return "\n".join(lines)


def _build_user_prompt(context: str) -> str:
    return (
        "Using the structured context below, write a short, interesting AI Insight of the Day. "
        "Describe what's happening in the market in a natural, narrative style, and weave in why "
        "it might matter for this kind of investor without explicitly listing their preferences "
        "back to them or explaining your reasoning. Do not provide financial advice and do not add "
        "a disclaimer sentence.\n\n" + context
    )


def _fetch_ai_insight_text(user_prompt: str) -> str | None:
    """Try to generate an insight via OpenRouter. Returns None if no key/model
    is configured, the request fails, times out, or returns empty content."""
    if not settings.openrouter_api_key or not settings.openrouter_model:
        return None

    url = f"{settings.openrouter_base_url.rstrip('/')}/chat/completions"
    headers = {"Authorization": f"Bearer {settings.openrouter_api_key}"}
    payload = {
        "model": settings.openrouter_model,
        "messages": [
            {"role": "system", "content": _AI_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "max_tokens": 300,
        "temperature": 0.7,
    }

    try:
        response = httpx.post(url, headers=headers, json=payload, timeout=OPENROUTER_TIMEOUT_SECONDS)
        response.raise_for_status()
        data = response.json()
        content = data["choices"][0]["message"]["content"]
    except Exception as exc:  # network errors, timeouts, bad JSON, non-2xx status, etc.
        print(f"[integrations] OpenRouter request failed, falling back: {exc}")
        return None

    content = (content or "").strip()
    return content or None


def _deterministic_insight(
    preferences: UserPreferences,
    coin_prices: list[dict[str, object]],
    market_news: list[dict[str, object]],
    variant: int = 0,
) -> str:
    movers = sorted(coin_prices, key=lambda item: item["change24h"], reverse=True)

    if movers:
        top = movers[0]
        lead = f"{top['symbol']} is {'up' if top['change24h'] >= 0 else 'down'} {abs(top['change24h']):.1f}% over the last 24 hours"
        if len(movers) > 1 and movers[-1]["symbol"] != top["symbol"]:
            bottom = movers[-1]
            lead += (
                f", while {bottom['symbol']} is {'up' if bottom['change24h'] >= 0 else 'down'} "
                f"{abs(bottom['change24h']):.1f}%"
            )
        lead += "."
    else:
        lead = "Markets are holding fairly steady across your selected assets today."

    opener = _INSIGHT_OPENERS[variant % len(_INSIGHT_OPENERS)].format(lead=lead)

    news_note = ""
    if market_news:
        # Rotate which headline gets referenced too, not just the framing, so a
        # regenerated insight can differ in substance when more than one item
        # is available, not just in wording.
        headline = market_news[variant % len(market_news)]["title"]
        news_note = f' Meanwhile, "{headline}" is part of today\'s broader conversation.'

    investor_phrase = _INVESTOR_PHRASES.get(preferences.investor_type, "investors like you")
    risk_phrase = _RISK_PHRASES.get(preferences.risk_level, "your selected risk level")
    closer = _INSIGHT_CLOSERS[variant % len(_INSIGHT_CLOSERS)].format(
        investor_phrase=investor_phrase, risk_phrase=risk_phrase
    )

    return f"{opener}{news_note} {closer}"


def _insight_id(content: str) -> str:
    """Derive the insight's feedback id from its actual text, not a fixed
    string. The insight's wording changes whenever live price data moves
    (which can be nearly every request), so a fixed id like "insight-today"
    would make a vote on one day's wording silently stick to completely
    different wording later. Identical content still reuses the same id, so
    a genuinely repeated insight keeps its vote."""
    digest = hashlib.sha256(content.encode()).hexdigest()[:12]
    return f"insight-{digest}"


MAX_INSIGHT_VARIANTS = 3


def generate_ai_insight(
    preferences: UserPreferences,
    coin_prices: list[dict[str, object]],
    market_news: list[dict[str, object]],
    feedback_items: list[dict[str, object]] | None = None,
    avoid_content: str | None = None,
    excluded_ids: set[str] | None = None,
) -> dict[str, object]:
    """Return the AI Insight of the Day: AI-generated via OpenRouter when a key
    and model are configured and the response passes a basic safety check,
    otherwise a deterministic fallback insight built from the same context.

    `avoid_content` is the text of an insight the user just gave a thumbs-down
    to (see `POST /dashboard/ai-insight/refresh`). When set, generation is
    steered away from repeating it: the live prompt asks explicitly for a
    different angle, and the deterministic fallback rotates through alternate
    phrasing/headline variants until it produces something different (rather
    than deterministically reproducing the exact rejected text, which is what
    a plain re-call would otherwise do given unchanged market data).

    `excluded_ids` are ids of insights the user has downvoted in the past
    (same idea as market-news/meme exclusion elsewhere in this module). This
    guards the plain dashboard load too: without live market movement, the
    deterministic fallback would otherwise regenerate byte-identical text to
    something already rejected, even outside the immediate replace flow."""
    excluded_ids = excluded_ids or set()

    if settings.openrouter_api_key and settings.openrouter_model:
        context = _build_ai_context(preferences, coin_prices, market_news, feedback_items)
        user_prompt = _build_user_prompt(context)
        if avoid_content:
            user_prompt += (
                "\n\nThe user gave a thumbs-down to this previous insight and wants something "
                f'different: "{avoid_content}"\nWrite a new insight with a different angle or '
                "focus than the one above. Do not repeat similar wording."
            )

        ai_content = _fetch_ai_insight_text(user_prompt)

        if ai_content and _contains_unsafe_wording(ai_content):
            print("[integrations] OpenRouter response failed the safety check, falling back")
            ai_content = None

        if ai_content and avoid_content and ai_content.strip() == avoid_content.strip():
            ai_content = None  # model echoed the rejected text; fall through to the deterministic path

        if ai_content and _insight_id(ai_content) in excluded_ids:
            ai_content = None  # matches a previously-downvoted insight; fall through to the deterministic path

        if ai_content:
            return {
                "id": _insight_id(ai_content),
                "title": "Your personalized crypto context",
                "content": ai_content,
                "source": "openrouter",
                "isFallback": False,
            }

    def _rejected(content: str) -> bool:
        if avoid_content and content.strip() == avoid_content.strip():
            return True
        return _insight_id(content) in excluded_ids

    fallback_content = _deterministic_insight(preferences, coin_prices, market_news)
    for variant in range(1, MAX_INSIGHT_VARIANTS):
        if not _rejected(fallback_content):
            break
        fallback_content = _deterministic_insight(preferences, coin_prices, market_news, variant=variant)

    return {
        "id": _insight_id(fallback_content),
        "title": "Your personalized crypto context",
        "content": fallback_content,
        "source": "deterministic",
        "isFallback": True,
    }
